import { fetchCountry } from "@/actions/countryAction";
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  weight: "400",
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const country = await fetchCountry();
  return (
    <html lang="en">
      <body className={`${outfit.className}`}>
        <Sidebar country={country} />
        <main>{children}</main>
      </body>
    </html>
  );
}
